export const TOAST_DURATION_MS = 3000
export const HABIT_NAME_MAX_LENGTH = 100
export const DAYS_TO_SHOW = 14
export const DEFAULT_HABIT_COLOR = '#6366f1'
export const MAX_STREAK_ITERATIONS = 3650 // safety cap ~10 years
export const COMPLETION_WINDOW_SHORT = 7
export const COMPLETION_WINDOW_LONG = 30
export const HEATMAP_DAYS = 365
export const CATEGORY_MAX_LENGTH = 50
